package com.capstone.tokenatm.controller;

import java.io.IOException;
import java.util.List;

import com.capstone.tokenatm.entity.ConfigEntity;
import com.capstone.tokenatm.service.ConfigRepository;
import com.capstone.tokenatm.service.ConfigService;
import com.capstone.tokenatm.service.EarnService;
import com.capstone.tokenatm.service.Request.RequestLogBody;
import com.capstone.tokenatm.service.Response.UpdateConfigResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.configurationprocessor.json.JSONException;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
// This means that this class is a Controller
public class ConfigController {
    @Autowired // This means to get the bean called LogRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ConfigRepository configRepository;

    @Autowired
    ConfigService configService;

    @GetMapping(path="/config")
    public @ResponseBody Iterable<ConfigEntity> getLogs() {
        // This returns a JSON or XML with the logs
        return configRepository.findAll();
    }

    @PostMapping(path="/config/")
    public @ResponseBody List<String> getLogsForStudent(@RequestBody RequestLogBody body) {
        return configRepository.findByType(body.getName());
    }
    @PostMapping("/config/update")
    public @ResponseBody UpdateConfigResponse updateToken(@RequestParam Integer id, @RequestParam String config_name) throws JSONException, IOException {
        return configService.updateConfigEntity(id, config_name);
    }
}
